/* Generated By:JavaCC: Do not edit this line. Compilador.java */
package Foo;
import Foo.Tabla_Simbolos;
import Foo.Simbolo.Tipo_simbolo;
import Foo.Simbolo.Tipo_variable;
import Foo.Simbolo.Clase_parametro;
import Foo.SimboloNoEncontradoException;
import Foo.TipoOperador.Tipo_Operador_Aditivo;
import Foo.TipoOperador.Tipo_Operador_Multiplicativo;
import Foo.TipoOperador.Tipo_Operador_Relacional;
import java.io.File;
import java.io.IOException;
import java.util.LinkedList;

public class Compilador implements CompiladorConstants {
  // IniCio del nivel de declaraciones anidadas
  public static int nivel = 0;

  // Variable de direccion por defecto a 0
  public static long dir = 0;

  public static Tabla_Simbolos tabla = new Tabla_Simbolos();

  public static void main(String args []) throws ParseException
  {
    /* nombre del fichero */
    String nombreArchivo;
    String path = "C:\u005c\u005cUsers\u005c\u005cGord\u005c\u005cDesktop\u005c\u005cprogramas\u005c\u005c";
    if (args [0].equals("-v"))
    {
      System.out.println("Compilacion en modo verbose");
      nombreArchivo = args [1];
    }
    else
    {
      System.out.println("Compilacion sin modo verbose");
      nombreArchivo = args [0];
    }
    /* Completar la ruta del path */
    path += nombreArchivo;
    System.out.println("LEYENDO FICHERO " + nombreArchivo + "\u005cn");
    try
    {
      /* Crear el parser con respecto al fichero */
      Compilador parser = new Compilador(new java.io.FileInputStream(path));
      // Inicializacion de la tabla de simbolos
      tabla.inicializar_tabla();
      int res = Compilador.programa();
      if (args [0].equals("-v"))
      {
        /* Mostrar total de tokens */
        TablaHash.mostrarTokensNormales();
        /* Mostrar total de identificadores */
        TablaHash.mostrarIdentificadores();
      }
      System.out.println("El fichero introducido es correcto");
    }
    catch (Exception e)
    {
      System.out.println("INCORRECTO");
      System.out.println(e.getMessage());
      Compilador.ReInit(System.in);
    }
    catch (Error e)
    {
      // Obtencion del error sintactico 
      int fila = CompiladorTokenManager.input_stream.getBeginLine();
      int columna = CompiladorTokenManager.input_stream.getBeginColumn();
      String tokenMalo = CompiladorTokenManager.input_stream.GetImage();
      ErrorLexico eL = new ErrorLexico(fila, columna, tokenMalo);
    }
  }

/* Construccion del analizador sintactico */

// Regla de programa
  static final public int programa() throws ParseException {
  Token tSim, t;
  Simbolo s;
  Simbolo.Tipo_simbolo tp_Sim;
    try {
      jj_consume_token(tPROGRAMA);
      // Guardado del nombre del programa
          t = jj_consume_token(tIDENTIFICADOR);
      // Insertar en la tabla de simbolos el token del programa
      // no se comprueba porque es el primero
      s = tabla.introducir_programa(t.image, dir);
      jj_consume_token(tPUNTYCOM);
      declaracion_variables();
      declaracion_acciones();
      bloque_sentencias();
      jj_consume_token(0);
      {if (true) return 0;}
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    {if (true) return 1;}
    }
    throw new Error("Missing return statement in function");
  }

// Regla de bloque_sentencias OK
  static final public void bloque_sentencias() throws ParseException {
  // Declaracion de variables
  Token t;
    try {
      jj_consume_token(tPRINCIPIO);
      lista_sentencias();
      t = jj_consume_token(tFIN);
      // Ocultar los parametros del nivel actual
      tabla.ocultar_parametros(nivel);
      // Detectado el fin de un bloque de sentencias
      // Mostrar el contenido de la tabla Hash
      tabla.mostrarTabla_Simbolos();
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de lista_sentencias OK EN DUDA
  static final public void lista_sentencias() throws ParseException {
    try {
      label_1:
      while (true) {
        sentencia();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tSI:
        case tMQ:
        case tESCRIBIR:
        case tLEER:
        case tIDENTIFICADOR:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de sentencia OK
  static final public void sentencia() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tLEER:
        leer();
        jj_consume_token(tPUNTYCOM);
        break;
      case tESCRIBIR:
        escribir();
        jj_consume_token(tPUNTYCOM);
        break;
      case tIDENTIFICADOR:
        asig_invoc();
        break;
      case tSI:
        seleccion();
        break;
      case tMQ:
        mientras_que();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

  static final public void asig_invoc() throws ParseException {
    try {
      jj_consume_token(tIDENTIFICADOR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tOPAS:
        asignacion();
        break;
      case tPUNTYCOM:
      case tPARENTESIS_IZDA:
        invocacion_accion();
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de asignacion OK
  static final public void asignacion() throws ParseException {
    try {
      jj_consume_token(tOPAS);
      expresion();
      jj_consume_token(tPUNTYCOM);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de lista_asignables OK
  static final public void lista_asignables() throws ParseException {
    try {
      identificadores();
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de leer OK
  static final public void leer() throws ParseException {
    try {
      jj_consume_token(tLEER);
      jj_consume_token(tPARENTESIS_IZDA);
      lista_asignables();
      jj_consume_token(tPARENTESIS_DCHA);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de escribir OK
  static final public void escribir() throws ParseException {
    try {
      jj_consume_token(tESCRIBIR);
      jj_consume_token(tPARENTESIS_IZDA);
      lista_escribibles();
      jj_consume_token(tPARENTESIS_DCHA);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de lista_escribibles OK
  static final public void lista_escribibles() throws ParseException {
    try {
      escribible();
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        jj_consume_token(tCOMA);
        escribible();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de lista_escribibles OK
  static final public void escribible() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tCONSTCHAR:
        jj_consume_token(tCONSTCHAR);
        break;
      case tCONSTCAD:
        jj_consume_token(tCONSTCAD);
        break;
      case tENTACAR:
        jj_consume_token(tENTACAR);
        jj_consume_token(tPARENTESIS_IZDA);
        jj_consume_token(tCONSTANTE_NUMERICA);
        jj_consume_token(tPARENTESIS_DCHA);
        break;
      case tIDENTIFICADOR:
        jj_consume_token(tIDENTIFICADOR);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de invocacion accion OK
  static final public void invocacion_accion() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPARENTESIS_IZDA:
        argumentos();
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      jj_consume_token(tPUNTYCOM);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

//Regla de mientras que OK
  static final public void mientras_que() throws ParseException {
    try {
      jj_consume_token(tMQ);
      expresion();
      lista_sentencias();
      jj_consume_token(tFMQ);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla para los argumentos OK
  static final public void argumentos() throws ParseException {
    try {
      jj_consume_token(tPARENTESIS_IZDA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tMINUS:
      case tNOT:
      case tTRUE:
      case tFALSE:
      case tENTACAR:
      case tCARAENT:
      case tCONSTCHAR:
      case tCONSTCAD:
      case tCONSTANTE_NUMERICA:
      case tIDENTIFICADOR:
      case tPARENTESIS_IZDA:
        lista_expresiones();
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      jj_consume_token(tPARENTESIS_DCHA);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de lista de expresiones
  static final public void lista_expresiones() throws ParseException {
    try {
      expresion();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_3;
        }
        jj_consume_token(tCOMA);
        expresion();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de expresion OK
  static final public RegistroExp expresion() throws ParseException {
  // Declaracion de expresiones a analizar
  RegistroExp tpExp1, tpExp2;
  TipoOperador op;

  boolean ok;
  RegistroExp regResult = new RegistroExp();
    try {
      // Obtencion de la primera expresion
          tpExp1 = expresion_simple();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tMAYOR:
        case tMENOR:
        case tIGUAL:
        case tMAI:
        case tMEI:
        case tNI:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
        op = operador_relacional();
        // Obtencion de la segunda expresion
              tpExp2 = expresion_simple();
        // Evaluacion de la expresion
        // Resultado de evaluar la expresion
        regResult = new RegistroExp();
        ok = true;

        // Evaluar el simbolo introducido
        switch(op.getOperadorRelacional()) {
          case IGUAL:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if (tpExp1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter, cadena o booleano");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if (tpExp2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter, cadena o booleano");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Verficar que los dos operandos son del mismo tipo
                  if (tpExp1.getTipo() == tpExp2.getTipo())
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador

                                        // OJO
                                int operando1 = tpExp1.getValorEnt();
                                int operando2 = tpExp2.getValorEnt();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 == operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // Error semantico de tipos distintos
                    ErrorSemantico eSM = new ErrorSemantico("Los operadores son distintos");
                  }
                }
                break;
                case MENOR:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if ((tpExp1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp1.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpExp2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp2.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Verficar que los dos operandos son del mismo tipo
                  if (tpExp1.getTipo() == tpExp2.getTipo())
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador

                                        // OJO
                                int operando1 = tpExp1.getValorEnt();
                                int operando2 = tpExp2.getValorEnt();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 < operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // Error semantico de tipos distintos
                    ErrorSemantico eSM = new ErrorSemantico("Los operadores son distintos");
                  }
                }
                break;
                case MENOR_IGUAL:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if ((tpExp1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp1.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpExp2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp2.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Verficar que los dos operandos son del mismo tipo
                  if (tpExp1.getTipo() == tpExp2.getTipo())
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador

                                        // OJO
                                int operando1 = tpExp1.getValorEnt();
                                int operando2 = tpExp2.getValorEnt();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 == operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // Error semantico de tipos distintos
                    ErrorSemantico eSM = new ErrorSemantico("Los operadores son distintos");
                  }
                }
                break;
                case NO_IGUAL:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if (tpExp1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter, cadena, booleano");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if (tpExp2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter, cadena o booleano");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Verficar que los dos operandos son del mismo tipo
                  if (tpExp1.getTipo() == tpExp2.getTipo())
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador

                                        // OJO
                                int operando1 = tpExp1.getValorEnt();
                                int operando2 = tpExp2.getValorEnt();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 != operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // Error semantico de tipos distintos
                    ErrorSemantico eSM = new ErrorSemantico("Los operadores son distintos");
                  }
                }
                break;
                case MAYOR_IGUAL:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if ((tpExp1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp1.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpExp2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp2.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Verficar que los dos operandos son del mismo tipo
                  if (tpExp1.getTipo() == tpExp2.getTipo())
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador

                                        // OJO
                                int operando1 = tpExp1.getValorEnt();
                                int operando2 = tpExp2.getValorEnt();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 >= operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // Error semantico de tipos distintos
                    ErrorSemantico eSM = new ErrorSemantico("Los operadores son distintos");
                  }
                }
                break;
                case MAYOR:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if ((tpExp1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp1.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpExp2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpExp2.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero " +
                                                                                                                "caracter o cadena");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Verficar que los dos operandos son del mismo tipo
                  if (tpExp1.getTipo() == tpExp2.getTipo())
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador

                                        // OJO
                                int operando1 = tpExp1.getValorEnt();
                                int operando2 = tpExp2.getValorEnt();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 > operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // Error semantico de tipos distintos
                    ErrorSemantico eSM = new ErrorSemantico("Los operadores son distintos");
                  }
                }
                default:
                        // No es un operador aditivo valido
                        ErrorSemantico eSM = new ErrorSemantico("El operador relacional es desconocido");
        }
        // Devolucion de la expresion
        {if (true) return regResult;}
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de operador_relacional OK
  static final public TipoOperador operador_relacional() throws ParseException {
  // Declaracion de variables
  TipoOperador op = new TipoOperador();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tIGUAL:
        jj_consume_token(tIGUAL);
      // Es el operador ==
      op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.IGUAL);
      {if (true) return op;}
        break;
      case tMENOR:
        jj_consume_token(tMENOR);
           // Es el operador <
           op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MENOR);
       {if (true) return op;}
        break;
      case tMEI:
        jj_consume_token(tMEI);
           // Es el operador <=
           op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MENOR_IGUAL);
       {if (true) return op;}
        break;
      case tNI:
        jj_consume_token(tNI);
           // Es el operador <>
           op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.NO_IGUAL);
       {if (true) return op;}
        break;
      case tMAI:
        jj_consume_token(tMAI);
           // Es el operador >=
           op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MAYOR_IGUAL);
       {if (true) return op;}
        break;
      case tMAYOR:
        jj_consume_token(tMAYOR);
           // Es el operador >
           op.setOperadorRelacional(TipoOperador.Tipo_Operador_Relacional.MAYOR);
       {if (true) return op;}
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla operador aditivo OK
  static final public TipoOperador operador_aditivo() throws ParseException {
  // Declaracion de variables
  TipoOperador op = new TipoOperador();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPLUS:
        jj_consume_token(tPLUS);
        // El operador es una suma
        op.setOperadorAditivo(TipoOperador.Tipo_Operador_Aditivo.SUMA);
        {if (true) return op;}
        break;
      case tMINUS:
        jj_consume_token(tMINUS);
                // El operaodr es una resta
            op.setOperadorAditivo(TipoOperador.Tipo_Operador_Aditivo.RESTA);
            {if (true) return op;}
        break;
      case tOR:
        jj_consume_token(tOR);
                // El operador es un OR
            op.setOperadorAditivo(TipoOperador.Tipo_Operador_Aditivo.OR);
            {if (true) return op;}
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// regla de expresion simple OK
  static final public RegistroExp expresion_simple() throws ParseException {
  // Declaracion de variables
  RegistroExp regTerm1, regTerm2, regResult;
  TipoOperador op;
  boolean ok;
    try {
      // Primer termino de la expresion
          regTerm1 = termino();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tPLUS:
        case tMINUS:
        case tOR:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_5;
        }
        // Operador de la expresion
              op = operador_aditivo();
        // Segundo termino de la expresion
              regTerm2 = termino();
        // Resultado de evaluar la expresion
        regResult = new RegistroExp();
        ok = true;

        // Evaluar el simbolo introducido
        switch(op.getOperadorAditivo()) {
          case SUMA:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if ((regTerm1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (regTerm1.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((regTerm2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (regTerm2.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 2 debe ser entero");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (regTerm1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && regTerm2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador
                                int operando1 = regTerm1.getValorEnt();
                                int operando2 = regTerm1.getValorEnt();

                                        // Suma de los operandos numericos
                                int resul = operando1 + operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorEnt(resul);
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                case RESTA:
                // El operador es una resta

                // Evaluar primer termino de la expresion
                if ((regTerm1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (regTerm1.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser entero");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((regTerm2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (regTerm2.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 2 debe ser entero");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (regTerm1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && regTerm2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador
                                int operando1 = regTerm1.getValorEnt();
                                int operando2 = regTerm1.getValorEnt();

                                        // Suma de los operandos numericos
                                int resul = operando1 - operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorEnt(resul);
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                case OR:
                // El operador es un OR logico

                // Evaluar primer termino de la expresion
                if ((regTerm1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (regTerm1.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 1 debe ser booleano");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((regTerm2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (regTerm2.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El operador 2 debe ser booleano");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (regTerm1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && regTerm2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.BOOLEANO);

                                        // Extracion de los valores numericos de cada operador
                                boolean operando1 = regTerm1.isValorBool();
                                boolean operando2 = regTerm1.isValorBool();

                                        // Suma de los operandos numericos
                                boolean resul = operando1 | operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                default:
                        // No es un operador aditivo valido
                        ErrorSemantico eSM = new ErrorSemantico("El operador aditivo es desconocido");
        }
        {if (true) return regResult;}
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// LOS OPERADORES SON AND Y ESAS MIERDAS EH
// Regla de termino OK
  static final public RegistroExp termino() throws ParseException {
  // Declaracion de factores y expresiones
  RegistroExp tpFactor1, tpFactor2;

  // Declaracion del operador
  TipoOperador op;
  boolean ok;
    try {
      // Evaluacion del primer factor
           tpFactor1 = factor();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tMULTIPLY:
        case tDIVIDE:
        case tAND:
        case tMOD:
        case tDIV:
          ;
          break;
        default:
          jj_la1[12] = jj_gen;
          break label_6;
        }
        // Evaluacion del operador multiplicativo
               op = operador_multiplicativo();
        // Evaluacion del segundo factor
               tpFactor2 = factor();
          // Expresion a devolver
          RegistroExp regResult = new RegistroExp();

          ok = true;

        // Evaluar el simbolo introducido
        switch(op.getOperadorMultiplicativo()) {
          case MULTIPLICACION:
                // El operador es una suma

                // Evaluar primer termino de la expresion
                if ((tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor1.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El factor 1 del producto " +
                                                                                                                "debe ser entero");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor2.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El factor 2 del producto " +
                                                                                                                "debe ser entero");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador
                                int operando1 = tpFactor1.getValorEnt();
                                int operando2 = tpFactor2.getValorEnt();

                                        // Multiplicacion de los operandos numericos
                                int resul = operando1 * operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorEnt(resul);
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                case DIVISION:
                // El operador es una resta

                // Evaluar primer termino de la expresion
                if ((tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor2.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El dividendo debe ser entero");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor2.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El divisor debe ser entero");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Comprobacion de que el segundo termino no es cero
                        int operando2 = tpFactor2.getValorEnt();

                        if (operando2 != 0)
                        {
                          // La operacion se puede efectuar
                          // Tipo de la nueva expresion
                              regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                          // Extracion de los valores numericos de cada operador
                                  int operando1 = tpFactor1.getValorEnt();


                                      // Cocientes de los operandos
                                  int resul = operando1 / operando2;

                              // Asignacion del resultado a la expresion resultado 
                              regResult.setValorEnt(resul);
                        }
                        else
                        {
                          // Error al dividir por cero
                          ErrorSemantico eSM = new ErrorSemantico("Division por cero");
                                  ok = false;
                        }
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                case MOD:
                // El operador es un OR logico

                // Evaluar primer termino de la expresion
                if ((tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor1.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El dividendo debe ser entero");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor2.getTipo() != Simbolo.Tipo_variable.ENTERO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El divisor debe ser entero");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Comprobacion de que el segundo termino no es cero
                        int operando2 = tpFactor2.getValorEnt();

                        if (operando2 != 0)
                        {
                          // La operacion se puede efectuar
                          // Tipo de la nueva expresion
                              regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                          // Extracion de los valores numericos de cada operador
                                  int operando1 = tpFactor1.getValorEnt();


                                      // Modulo de los operandos
                                  int resul = operando1 % operando2;

                              // Asignacion del resultado a la expresion resultado 
                              regResult.setValorEnt(resul);
                        }
                        else
                        {
                          // Error al dividir por cero
                          ErrorSemantico eSM = new ErrorSemantico("Modulo por cero");
                                  ok = false;
                        }
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                case AND:
                // El operador es una AND logica

                // Evaluar primer termino de la expresion
                if ((tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor1.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El factor 1 debe ser booleano");
                          ok = false;
                }
                // Evaluar segundo termino de la expresion
                if ((tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                        && (tpFactor2.getTipo() != Simbolo.Tipo_variable.BOOLEANO))
                {
                          ErrorSemantico eSM = new ErrorSemantico("El factor 2 debe ser booleano");
                          ok = false;
                }
                // Comprobar que todo ha ido bien y evaluar la expresion
                if (ok) {
                  // Calculo de la expresion
                  if (tpFactor1.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO
                                && tpFactor2.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO)
                  {
                        // Tipo de la nueva expresion
                        regResult.setTipo(Simbolo.Tipo_variable.ENTERO);

                                        // Extracion de los valores numericos de cada operador
                                boolean operando1 = tpFactor1.isValorBool();
                                boolean operando2 = tpFactor2.isValorBool();

                                        // Operacion logica AND de los operandos
                                boolean resul = operando1 & operando2;

                                // Asignacion del resultado a la expresion resultado 
                        regResult.setValorBool(resul);
                  }
                  else
                  {
                    // El tipo de la expresion es desconocido
                    regResult.setTipo(Simbolo.Tipo_variable.DESCONOCIDO);
                  }
                }
                break;
                default:
                        // No es un operador aditivo valido
                        ErrorSemantico eSM = new ErrorSemantico("El operador multiplicativo" +
                                                                                                        " es desconocido");
        }
        // Devolucion de la expresion
        {if (true) return regResult;}
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de operador multiplicativo OK
  static final public TipoOperador operador_multiplicativo() throws ParseException {
  // Declaracion de variables
  TipoOperador op = new TipoOperador();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tMULTIPLY:
        jj_consume_token(tMULTIPLY);
      // El operador es una multiplicacion
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.MULTIPLICACION);
      {if (true) return op;}
        break;
      case tDIVIDE:
        jj_consume_token(tDIVIDE);
          // El operador es un cociente (opcion 1)
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.DIVISION);
      {if (true) return op;}
        break;
      case tDIV:
        jj_consume_token(tDIV);
          // El operador es un cociente (opcion 2)
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.DIVISION);
      {if (true) return op;}
        break;
      case tMOD:
        jj_consume_token(tMOD);
          // El operador es un modulo o residuo
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.MOD);
      {if (true) return op;}
        break;
      case tAND:
        jj_consume_token(tAND);
          // El operador es una AND logica
      op.setOperadorMultiplicativo(TipoOperador.Tipo_Operador_Multiplicativo.AND);
      {if (true) return op;}
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de factor OK
  static final public RegistroExp factor() throws ParseException {
   // Declaracion de factores y expresiones
   RegistroExp tpFactor, tpExp;
   RegistroExp result = new RegistroExp();

        // Token a procesar
   Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tNOT:
        jj_consume_token(tNOT);
        tpFactor = factor();
      // Comprobacion de si es o no booleano
      if ((tpFactor.getTipo() != Simbolo.Tipo_variable.BOOLEANO)
          && (tpFactor.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
      {
        // Comprobacion de si es booleano o no 
        ErrorSemantico eSM = new ErrorSemantico("Tipo incompatible. Se esperaba BOOLEANO");
      }
      // Devuelve el tipo de factor
      {if (true) return tpFactor;}
        break;
      case tMINUS:
        jj_consume_token(tMINUS);
        tpFactor = factor();
      // Comprobacion de si es o no booleano
      if ((tpFactor.getTipo() != Simbolo.Tipo_variable.ENTERO)
          && (tpFactor.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
      {
        // Comprobacion de si es booleano o no 
        ErrorSemantico eSM = new ErrorSemantico("Tipo incompatible. Se esperaba ENTERO");
      }
      // Devuelve el tipo de factor
      {if (true) return tpFactor;}
        break;
      case tPARENTESIS_IZDA:
        jj_consume_token(tPARENTESIS_IZDA);
        tpExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
          // Devuelve la expresiom normal
          {if (true) return tpExp;}
        break;
      case tENTACAR:
        jj_consume_token(tENTACAR);
        jj_consume_token(tPARENTESIS_IZDA);
        tpExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
          // Comprobacion de si es entera la expresion
          if ((tpExp.getTipo() != Simbolo.Tipo_variable.ENTERO)
                  && (tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
          {
            // Comprobacion de si es booleano o no 
        ErrorSemantico eSM = new ErrorSemantico("La expresion no se puede convertir " +
                                                                                        " en un caracter valido");
          }
          else
          {
            // Es un entero y se comprueba que no hay desbordamiento
            int valor = tpExp.getValorEnt();

            // Error de desbordamiento
            ErrorSemantico eSM = new ErrorSemantico();

            if (!eSM.hayDesbordamiento(valor))
            {
              // Comprobacion de si es booleano o no 
          eSM = new ErrorSemantico("Desbordamiento detectado");
                }
          }
          {if (true) return tpExp;}
        break;
      case tCARAENT:
        jj_consume_token(tCARAENT);
        jj_consume_token(tPARENTESIS_IZDA);
        tpExp = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
          if ((tpExp.getTipo() != Simbolo.Tipo_variable.CHAR)
                        && (tpExp.getTipo() != Simbolo.Tipo_variable.DESCONOCIDO))
          {
                // Comprobacion de si es o no caracter
        ErrorSemantico eSM = new ErrorSemantico("Tipo incompatible. Se esperaba CARACTER");
          }
          {if (true) return tpExp;}
        break;
      case tIDENTIFICADOR:
        jj_consume_token(tIDENTIFICADOR);

        break;
      case tCONSTANTE_NUMERICA:
        t = jj_consume_token(tCONSTANTE_NUMERICA);
          // Obtener el valor del token y pasarlo a entero para guardarlo
          int valor = Integer.parseInt(t.image);
          result.setValorEnt(valor);

          // Tipo de la variable entero
          result.setTipo(Simbolo.Tipo_variable.ENTERO);

          // Devolucion del resultado
          {if (true) return result;}
        break;
      case tCONSTCHAR:
        t = jj_consume_token(tCONSTCHAR);
           // Guardar el contenido de la cadena
          result.setValorString(t.image);
          // Char
          result.setTipo(Simbolo.Tipo_variable.CHAR);
          // Devolucion del resultado
          {if (true) return result;}
        break;
      case tCONSTCAD:
        t = jj_consume_token(tCONSTCAD);
          // Guardar el contenido de la cadena
          result.setValorString(t.image);
          // Tipo cadena de caracteres
          result.setTipo(Simbolo.Tipo_variable.CADENA);
          // Devolucion del resultado
          {if (true) return result;}
        break;
      case tTRUE:
        jj_consume_token(tTRUE);
          // Guardar el contenido de la cadena
          result.setValorBool(true);
          // Tipo cadena de caracteres
          result.setTipo(Simbolo.Tipo_variable.BOOLEANO);
          // Devolucion del resultado
          {if (true) return result;}
        break;
      case tFALSE:
        jj_consume_token(tFALSE);
          // Guardar el contenido de la cadena
          result.setValorBool(false);
          // Tipo cadena de caracteres
          result.setTipo(Simbolo.Tipo_variable.BOOLEANO);
          // Devolucion del resultado
          {if (true) return result;}
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de seelccion OK
  static final public void seleccion() throws ParseException {
    try {
      jj_consume_token(tSI);
      expresion();
      jj_consume_token(tENT);
      lista_sentencias();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tSI_NO:
        jj_consume_token(tSI_NO);
        lista_sentencias();
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      jj_consume_token(tFSI);
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de declaracion_acciones OK
  static final public void declaracion_acciones() throws ParseException {
    try {
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tACCION:
          ;
          break;
        default:
          jj_la1[16] = jj_gen;
          break label_7;
        }
        declaracion_accion();
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de declaracion_Accion OK
  static final public void declaracion_accion() throws ParseException {
    try {
      cabecera_accion();
      jj_consume_token(tPUNTYCOM);
      declaracion_variables();
      declaracion_acciones();
      bloque_sentencias();
      // Eliminacion de variables
      tabla.eliminar_variables(nivel);
      // Eliminar las acciones
      tabla.eliminar_acciones(nivel);
      // Eliminar los parametros ocultos
      tabla.eliminar_parametros_ocultos(nivel + 1);
      // Decrementar el nivel porque se cierra un bloque       
      nivel--;
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de cabecera_accion OK
  static final public void cabecera_accion() throws ParseException {
  Token tId;
  Simbolo s = null;
  Simbolo.Tipo_simbolo tp_Sim;
  boolean ok = false;
  // Lista de parametros de la accion
  LinkedList < LinkedList < Simbolo > > listaDeParametros = new LinkedList < LinkedList < Simbolo > > ();
    try {
      jj_consume_token(tACCION);
      tId = jj_consume_token(tIDENTIFICADOR);
      // Insertar en la tabla de simbolos el nuevo identificador
      try
      {
        s = tabla.introducir_accion(tId.image, nivel, dir);
        ok = true;
      }
      catch (AccionRepetidaException aRepExcep)
      {
        // El simbolo ya existe en la tabla de simbolos
        aRepExcep.accionRepetidaExcepcion(tId.image);
      }
      // Incrementar el nivel actual
      nivel++;
      // Procesamiento de los parametros
          listaDeParametros = parametros_formales();
      // Se ha efectuado con exito
      if (ok)
      {
        for (int i = 0; i < listaDeParametros.size(); i++)
        {
          // Añadir la lista de parametros al simbolo
          s.anyadirParametrosAccion(listaDeParametros.get(i));
        }
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla de parametros formales OK
  static final public LinkedList < LinkedList < Simbolo > > parametros_formales() throws ParseException {
  // Lista global de listas de identificadores
  LinkedList < LinkedList < Simbolo > > parametros = new LinkedList < LinkedList < Simbolo > > ();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPARENTESIS_IZDA:
        parametros = lista_parametros();
      // Guardado de la lista de parametros procesada
      tabla.asignarListaParametros(parametros);
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      {if (true) return tabla.getListasParametros();}
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla para lista_parametros OK
  static final public LinkedList < LinkedList < Simbolo > > lista_parametros() throws ParseException {
  // Lista global de listas de identificadores
  LinkedList < LinkedList < Simbolo > > listaGlobal = new LinkedList < LinkedList < Simbolo > > ();
  // Lista de identificadores
  LinkedList < Simbolo > lista = new LinkedList < Simbolo > ();
    try {
      jj_consume_token(tPARENTESIS_IZDA);
      lista = parametros();
      // Vaciar lista de identificadores de parametros para evitar su resinsercion
      listaGlobal.add(lista);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tPUNTYCOM:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_8;
        }
        jj_consume_token(tPUNTYCOM);
        lista = parametros();
      listaGlobal.add(lista);
      }
      jj_consume_token(tPARENTESIS_DCHA);
      {if (true) return listaGlobal;}
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de parametros OK
  static final public LinkedList < Simbolo > parametros() throws ParseException {
  // Declaracion de variables
  // Simbolo a guardar en la tabla de simbolos
  Simbolo s;
  // Clase de parametro y tipo de variable del simbolo a introducir
  Simbolo.Clase_parametro cl_Param;
  Simbolo.Tipo_variable tipo_Var;
  // Lista de simbolos leidos a almacenar en la tabla de simbolos
  LinkedList < Simbolo > lista = new LinkedList < Simbolo > ();
  // Lista de identificadores procesados
  LinkedList < String > listaIdentificadores = new LinkedList < String > ();
    try {
      // Lectura del tipo de clase y del tipo de parametro
          cl_Param = clase_parametros();
      tipo_Var = tipos_variables();
      listaIdentificadores = identificadores();
      // Tamaño de la lista de identificadores
      int dimension = listaIdentificadores.size();
      // Identificador del simbolo a procesar
      String identificadorActual;
      // Bucle de recorrido de la lista de identificadores
      for (int i = 0; i < dimension; i++)
      {
        // Obtener identificador actual
        identificadorActual = listaIdentificadores.get(i);
        // Comprobar que existe o no simbolo en la tabla
        try
        {
          // Insercion del parametro en la tabla de simbolos
          s = tabla.introducir_parametro(identificadorActual, tipo_Var, cl_Param, nivel, dir);
          // Añadir parametro a la lista de parametros
          lista.add(s);
        }
        catch (ParametroRepetidoException pRepExcep)
        {
          // El parametro ya esta repetido 
          pRepExcep.parametroRepetidoExcepcion(identificadorActual);
        }
      }
      // Devolucion de la lista de parametros
      {if (true) return lista;}
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de declaracion variables OK
  static final public void declaracion_variables() throws ParseException {
  // Declaracion de variables 
  Token t;
    try {
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tENTERO:
        case tBOOLEANO:
        case tCARACTER:
          ;
          break;
        default:
          jj_la1[19] = jj_gen;
          break label_9;
        }
        declaracion();
        t = jj_consume_token(tPUNTYCOM);
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla para los tipos de variables OK
  static final public Simbolo.Tipo_variable tipos_variables() throws ParseException {
  // Declaracion de variable
  Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tENTERO:
        t = jj_consume_token(tENTERO);
        break;
      case tCARACTER:
        t = jj_consume_token(tCARACTER);
        break;
      case tBOOLEANO:
        t = jj_consume_token(tBOOLEANO);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      // Control del tipo token
      switch (t.kind)
      {
        case tENTERO :
        // Es token tENTERO
        {if (true) return Simbolo.Tipo_variable.ENTERO;}
        break;
        case tCARACTER :
        // Es token tCARACTER
        {if (true) return Simbolo.Tipo_variable.CHAR;}
        break;
        case tCONSTCAD :
        // Es token tCARACTER
        {if (true) return Simbolo.Tipo_variable.CADENA;}
        break;
        case tBOOLEANO :
        // Es token tBOOLEANO
        {if (true) return Simbolo.Tipo_variable.BOOLEANO;}
        break;
        default :
        // No es niguno de los anteriores es DESCONOCIDO
        {if (true) return Simbolo.Tipo_variable.DESCONOCIDO;}
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla de declaracion OK
  static final public void declaracion() throws ParseException {
  // Declaracion de variables
  Token t;
  Simbolo.Tipo_variable tp_Var;
  LinkedList < String > lista = new LinkedList < String > ();
  // Variable para guardar el identificador del simbolo a introducir
  String identificadorActual;
  Simbolo s;
    try {
      tp_Var = tipos_variables();
      lista = identificadores();
      // Tamaño de la lista de identificadores
      int dimension = lista.size();
      //Bucle de recorrido de insercion de variables
      for (int i = 0; i < dimension; i++)
      {
        // Obtencion del identificador actual
        identificadorActual = lista.get(i);
        // Simbolo ya existente en la tabla de simbolos
        try
        {
          // introducir el nuevo simbolo
          tabla.introducir_variable(identificadorActual, tp_Var, nivel, dir);
        }
        catch (VariableRepetidaException vRepExcep)
        {
          // El identificador ya existe en la tabla de simbolos
          vRepExcep.variableRepetidaExcepcion(identificadorActual);
        }
      }
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
  }

// Regla para los identificadores OK
  static final public LinkedList < String > identificadores() throws ParseException {
  // Declaracion de una lista auxiliar de identificadores
  Token t;
  // Lista de identificadores (parametros o variables)
  LinkedList < String > listaIdentificadores = new LinkedList < String > ();
    try {
      // Coger primer identificador
          t = jj_consume_token(tIDENTIFICADOR);
      // Añadir el identificador a lista
      listaIdentificadores.add(t.image);
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_10;
        }
        jj_consume_token(tCOMA);
        // Coger los siguientes identificadores
            t = jj_consume_token(tIDENTIFICADOR);
      // Añadir el identificador a lista
      listaIdentificadores.add(t.image);
      }
      {if (true) return listaIdentificadores;}
    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// Regla para las clases de parametros OK
  static final public Simbolo.Clase_parametro clase_parametros() throws ParseException {
  // Declaracion de variables
  Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tVAL:
        t = jj_consume_token(tVAL);
        break;
      case tREF:
        t = jj_consume_token(tREF);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (t.kind == tVAL)
      {
        // Es token tVAL
        {if (true) return Simbolo.Clase_parametro.VAL;}
      }
      else if (t.kind == tREF)
      {
        // Es tokeb tREF
        {if (true) return Simbolo.Clase_parametro.REF;}
      }
      else
      {
        // Clase de parametro erroneo
        System.out.println("La clase de parametro no es correcta");
      }
      // El tipo de clase ha sido procesada

    } catch (ParseException e) {
    ErrorSintactico eS = new ErrorSintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x88000000,0x88000000,0x80000,0x0,0x0,0x0,0x400400,0x0,0x7e000,0x7e000,0x200600,0x200600,0x101800,0x101800,0x400400,0x20000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x100006,0x100006,0xa00000,0x400000,0x160400,0x800000,0x9e0f00,0x400000,0x0,0x0,0x0,0x0,0x18,0x18,0x9e0f00,0x0,0x1000,0x800000,0x200000,0xe0,0xe0,0x400000,0x6000,};
   }

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[57];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 23; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 57; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
