/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package Foo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int tPLUS = 9;
  /** RegularExpression Id. */
  int tMINUS = 10;
  /** RegularExpression Id. */
  int tMULTIPLY = 11;
  /** RegularExpression Id. */
  int tDIVIDE = 12;
  /** RegularExpression Id. */
  int tMAYOR = 13;
  /** RegularExpression Id. */
  int tMENOR = 14;
  /** RegularExpression Id. */
  int tIGUAL = 15;
  /** RegularExpression Id. */
  int tMAI = 16;
  /** RegularExpression Id. */
  int tMEI = 17;
  /** RegularExpression Id. */
  int tNI = 18;
  /** RegularExpression Id. */
  int tOPAS = 19;
  /** RegularExpression Id. */
  int tAND = 20;
  /** RegularExpression Id. */
  int tOR = 21;
  /** RegularExpression Id. */
  int tNOT = 22;
  /** RegularExpression Id. */
  int tPROGRAMA = 23;
  /** RegularExpression Id. */
  int tVAR = 24;
  /** RegularExpression Id. */
  int tPRINCIPIO = 25;
  /** RegularExpression Id. */
  int tFIN = 26;
  /** RegularExpression Id. */
  int tSI = 27;
  /** RegularExpression Id. */
  int tENT = 28;
  /** RegularExpression Id. */
  int tSI_NO = 29;
  /** RegularExpression Id. */
  int tFSI = 30;
  /** RegularExpression Id. */
  int tMQ = 31;
  /** RegularExpression Id. */
  int tFMQ = 32;
  /** RegularExpression Id. */
  int tESCRIBIR = 33;
  /** RegularExpression Id. */
  int tLEER = 34;
  /** RegularExpression Id. */
  int tMOD = 35;
  /** RegularExpression Id. */
  int tDIV = 36;
  /** RegularExpression Id. */
  int tENTERO = 37;
  /** RegularExpression Id. */
  int tBOOLEANO = 38;
  /** RegularExpression Id. */
  int tCARACTER = 39;
  /** RegularExpression Id. */
  int tTRUE = 40;
  /** RegularExpression Id. */
  int tFALSE = 41;
  /** RegularExpression Id. */
  int tENTACAR = 42;
  /** RegularExpression Id. */
  int tCARAENT = 43;
  /** RegularExpression Id. */
  int tACCION = 44;
  /** RegularExpression Id. */
  int tVAL = 45;
  /** RegularExpression Id. */
  int tREF = 46;
  /** RegularExpression Id. */
  int tDIGITO = 47;
  /** RegularExpression Id. */
  int tLETRA = 48;
  /** RegularExpression Id. */
  int tCHAR = 49;
  /** RegularExpression Id. */
  int tSTRING = 50;
  /** RegularExpression Id. */
  int tCONSTANTE_NUMERICA = 51;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 52;
  /** RegularExpression Id. */
  int tPUNTYCOM = 53;
  /** RegularExpression Id. */
  int tCOMA = 54;
  /** RegularExpression Id. */
  int tPARENTESIS_IZDA = 55;
  /** RegularExpression Id. */
  int tPARENTESIS_DCHA = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ComentLinea = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"%%\"",
    "\"%%\"",
    "<token of kind 7>",
    "<SINGLE_LINE_COMMENT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\":=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"programa\"",
    "\"var\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"mod\"",
    "\"div\"",
    "\"entero\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "<tDIGITO>",
    "<tLETRA>",
    "<tCHAR>",
    "<tSTRING>",
    "<tCONSTANTE_NUMERICA>",
    "<tIDENTIFICADOR>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
